# Generated by Django 3.2.25 on 2026-03-24 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_app', '0004_remove_course_modules_course_course_embedding_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aiquiz',
            options={'verbose_name': 'AI Generated Quiz', 'verbose_name_plural': 'AI Generated Quizzes'},
        ),
        migrations.AlterModelOptions(
            name='lesson',
            options={'ordering': ['order'], 'verbose_name': 'Video Lesson', 'verbose_name_plural': 'Video Lessons'},
        ),
        migrations.AlterModelOptions(
            name='module',
            options={'ordering': ['order'], 'verbose_name': 'Course Chapter', 'verbose_name_plural': 'Course Chapters'},
        ),
        migrations.AddField(
            model_name='course',
            name='raw_modules',
            field=models.TextField(blank=True, db_column='modules', null=True),
        ),
        migrations.AddField(
            model_name='lesson',
            name='duration',
            field=models.CharField(blank=True, help_text='e.g., 11:31', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='completed_lessons',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.DeleteModel(
            name='LessonProgress',
        ),
    ]
